// A Makefile for building the assembly code generated by the `adder` compiler and the Rust program that calls it. The Makefile defines rules for compiling the S-expression tests into assembly code, assembling the code into an object file, creating a static library, and compiling the Rust program that links against the library.
// The `test/%.s` rule compiles a S-expression test file into an assembly file using the `adder` compiler. The `test/%.run` rule assembles the generated assembly code, creates a static library, and compiles the Rust program that calls the assembly code. The `.PRECIOUS` directive ensures that intermediate files are not deleted if the build process is interrupted.

.PRECIOUS: test/%.s
test/%.s: test/%.snek src/main.rs
	cargo run -- $< test/$*.s

test/%.run: test/%.s runtime/start.rs
	nasm -f elf64 test/$*.s -o runtime/our_code.o
	ar rcs runtime/libour_code.a runtime/our_code.o
	rustc -L runtime/ runtime/start.rs -o test/$*.run